# ISCB-Africa ASBCB 2025

## Lagoon Beach Hotel & Conference Center, Cape Town, South Africa

**Date of the session:** April 10, 2025

**Instructor(s)/Affiliation(s):** Loni Taylor, Meharry Medical College, Nashville, TN, USA. Bishnu Sarker, Meharry Medical College, Nashville, TN, USA. Animesh Acharjee, University of Birmingham, UK.

# Setting up your workspace

### 1. **Overview**
In this section, we will go over how to configure your environment and the basic packages used in python programming that will carry over into further applications. Jupyter notebooks are handy for installing and running python.

---

###  2. **Prerequisites**
- **Python 3.7+**
- Basic knowledge of Python programming
- Install **pandas**, **numpy** and **sklearn**

---

### 3. Step 1: Installing the Required Packages
Before running the codes, make sure to have **pandas**, **numpy** and **sklearn** installed.

    ```python
    !pip install pandas numpy sklearn
    ```
---

### 3. Step 2: Setting up Project Directory
Create a new directory (folder) and navigate to it. 
1. Create folder `Tutorials`.
    - Use `%mkdir {file_name}` to make a file directory through Jupyter. 
    ---
2. Download the notebooks in the tutorial github and place them in this folder 


```

## Data Loading
Now we are going to load the data as a pandas DataFrame into our notebook. Use the dataset(s) provided in this Github.
 
--- 

### Install pandas
`Pandas` is a python library that utilizes a table like structure called a DataFrame. The DataFrame has many functions used for data analysis, visualization, wrangling, and many others. 

```python
!pip install pandas
```

--- 

#### Load in the dataset
Use `pd.read_csv()` to read in a dataset as a pandas DataFrame

In [1]:
import pandas as pd

data = pd.read_csv('path to data/datafile.csv') 
#replace with path to data and repeat with new variable declarations for each omic
data

,Unnamed: 0,H045,H109,H024,H056,H079,H164,H059,H167,H113,...,H178,H166,H174,H177,H259,H175,H179,H050,H180,H229
0,ENSG00000244734,4.558644,2.721512,9.938456,13.278004,6.086874,2.571839,4.938961,1.528848,2.286122,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ENSG00000158528,11.741854,13.287432,2.341006,3.232874,11.940820,11.506818,5.483675,2.618869,2.812801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENSG00000198478,8.921456,2.721512,12.381452,8.106266,4.889503,12.756213,3.593890,4.119490,5.220041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENSG00000175445,12.686458,10.925985,1.528848,1.528848,13.340588,10.885547,11.194029,11.599981,2.286122,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ENSG00000174469,2.644946,12.648355,1.528848,13.565210,5.476914,10.975187,7.944246,2.618869,2.286122,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ENSG00000111328,10.059942,10.361200,8.152703,7.737858,8.274131,9.069614,9.272260,9.321016,9.543043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,ENSG00000165474,1.528848,1.528848,1.528848,2.417160,2.270282,1.528848,1.528848,1.528848,1.528848,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,ENSG00000164061,5.771337,5.359180,6.059008,5.495087,5.102382,6.212773,4.161332,6.411407,4.940975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,ENSG00000166816,1.528848,2.383843,2.341006,3.232874,1.528848,1.528848,1.528848,3.037599,1.528848,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,ENSG00000165972,5.256267,7.360436,5.715771,5.789100,6.316072,7.032524,6.714135,4.710281,7.437088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Explaination:
- `pd.read_csv()` Will read in a 'csv' file

Your data is now loaded and ready for operations.